import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { OnboardingProvider } from "../context/OnboardingContext";


const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Troms",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head>
      
          {process.env.NEXT_PUBLIC_ENV === "production" && (
            <>
              <script
                id="meta-pixel"
                dangerouslySetInnerHTML={{
                  __html: `
            !function(f,b,e,v,n,t,s)
            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window, document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '1335765837984569');
            fbq('track', 'PageView');
          `,
                }}
              />
              <noscript>
                <img
                  height="1"
                  width="1"
                  style={{ display: "none" }}
                  src="https://www.facebook.com/tr?id=1335765837984569&ev=PageView&noscript=1"
                />
              </noscript>
            </>
          )}
        </head> */}
 <head>
        {/* Facebook Pixel */}
        {process.env.NEXT_PUBLIC_ENV === "production" && (
          <>
            <script
              id="meta-pixel"
              dangerouslySetInnerHTML={{
                __html: `
                  !function(f,b,e,v,n,t,s)
                  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
                  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
                  n.queue=[];t=b.createElement(e);t.async=!0;
                  t.src=v;s=b.getElementsByTagName(e)[0];
                  s.parentNode.insertBefore(t,s)}(window, document,'script',
                  'https://connect.facebook.net/en_US/fbevents.js');
                  fbq('init', '1335765837984569');
                  fbq('track', 'PageView');
                `,
              }}
            />
            <noscript>
              <img
                height="1"
                width="1"
                style={{ display: "none" }}
                src="https://www.facebook.com/tr?id=1335765837984569&ev=PageView&noscript=1"
              />
            </noscript>
          </>
        )}

        {/* Google Tag Manager */}
        {process.env.NEXT_PUBLIC_ENV === "production" && (
          <script
            id="gtm-script"
            dangerouslySetInnerHTML={{
              __html: `
                (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
                })(window,document,'script','dataLayer','GTM-M43F4XST');
              `,
            }}
          />
        )}
      </head>

      <body className={`${inter.variable}`}>
        <OnboardingProvider>{children}</OnboardingProvider>
      </body>
    </html>
  );
}



